extend type Deal {
  """
  ✨ Implicit foreign key field based on `Deal`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID! @fdc_generated(from: "Deal.organization", purpose: IMPLICIT_REF_FIELD)
}
extend type Document {
  """
  ✨ Implicit foreign key field based on `Document`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID @fdc_generated(from: "Document.organization", purpose: IMPLICIT_REF_FIELD)
}
extend type Event {
  """
  ✨ Implicit foreign key field based on `Event`.`deal`. It must match the value of `Deal`.`id`. See `@ref` for how to customize it.
  """
  dealId: UUID @fdc_generated(from: "Event.deal", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Event`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID @fdc_generated(from: "Event.organization", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Event`.`ticket`. It must match the value of `Ticket`.`id`. See `@ref` for how to customize it.
  """
  ticketId: UUID @fdc_generated(from: "Event.ticket", purpose: IMPLICIT_REF_FIELD)
}
extend type Metric {
  """
  ✨ Implicit foreign key field based on `Metric`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID @fdc_generated(from: "Metric.organization", purpose: IMPLICIT_REF_FIELD)
}
extend type Person {
  """
  ✨ Implicit foreign key field based on `Person`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID @fdc_generated(from: "Person.organization", purpose: IMPLICIT_REF_FIELD)
}
extend type Ticket {
  """
  ✨ Implicit foreign key field based on `Ticket`.`contact`. It must match the value of `Person`.`id`. See `@ref` for how to customize it.
  """
  contactId: UUID @fdc_generated(from: "Ticket.contact", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Ticket`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID @fdc_generated(from: "Ticket.organization", purpose: IMPLICIT_REF_FIELD)
}
