# Organization Mutations
mutation CreateOrganization($data: Organization_Data!) @auth(level: PUBLIC) {
  organization_insert(data: $data)
}

mutation UpdateOrganization($id: UUID!, $data: Organization_Data!) @auth(level: PUBLIC) {
  organization_update(id: $id, data: $data)
}

mutation UpsertOrganization($data: Organization_Data!) @auth(level: PUBLIC) {
  organization_upsert(data: $data)
}

# Person Mutations
mutation CreatePerson($data: Person_Data!) @auth(level: PUBLIC) {
  person_insert(data: $data)
}

mutation UpdatePerson($id: UUID!, $data: Person_Data!) @auth(level: PUBLIC) {
  person_update(id: $id, data: $data)
}

# Ticket Mutations
mutation CreateTicket($data: Ticket_Data!) @auth(level: PUBLIC) {
  ticket_insert(data: $data)
}

# Event Mutations
mutation LogEvent($data: Event_Data!) @auth(level: PUBLIC) {
  event_insert(data: $data)
}

# Metric Mutations
mutation RecordMetric($data: Metric_Data!) @auth(level: PUBLIC) {
  metric_insert(data: $data)
}
