/**
 * Section 4 — LOADER: 8-Stage Universal Ingestion Pipeline
 *
 * Real implementation of all 8 stages:
 *   S1 Analyzer   — SHA-256 fingerprint, envelope with metadata
 *   S2 Classifier — data_kind detection, domain mapping, PII sensitivity scan
 *   S3 Filter     — Idempotency check (D1 fingerprints), tenant validation
 *   S4 Refiner    — Split composites, extract cross-ref IDs, normalize field names
 *   S5 Extractor  — Map to canonical schema, extract text/file metadata
 *   S6 Validator  — Required field checks, type validation, warning vs error
 *   S7 Split Router — Generate write plan (Spine / Context / Audit targets)
 *   S8 Writers    — Execute write plan, enqueue async analysis
 */

export interface IngestionContext {
  tenant_id: string;
  source: string;
  requestId: string;
  category?: string;
  user_id?: string;
  account_id?: string;
  team_id?: string;
  user_role?: string;
  /** Cloudflare D1 binding for fingerprint dedup */
  db?: D1Database;
  /** Spine v2 store URL */
  storeUrl?: string;
  /** THINK_QUEUE for async analysis */
  thinkQueue?: Queue;
}

/** Enriched envelope that accumulates metadata through stages */
export interface PipelineEnvelope {
  /** Original raw data */
  raw: any;
  /** SHA-256 fingerprint of the raw payload */
  fingerprint: string;
  /** Metadata accumulated by stages */
  meta: {
    source: string;
    tenant_id: string;
    request_id: string;
    received_at: string;
    data_kind: 'entity' | 'activity' | 'event' | 'file' | 'unknown';
    domain: string;
    sensitivity: 'public' | 'internal' | 'confidential' | 'restricted';
    pii_fields: string[];
    entity_type: string;
    is_duplicate: boolean;
    validation_errors: string[];
    validation_warnings: string[];
  };
  /** Canonical extracted fields */
  canonical: Record<string, unknown>;
  /** Write plan generated by S7 */
  write_plan: {
    spine: boolean;
    context_store: boolean;
    audit: boolean;
    targets: string[];
  };
  /** Sub-entities (from composite splits in S4) */
  children: any[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────

async function sha256(data: string): Promise<string> {
  const encoder = new TextEncoder();
  const buf = await crypto.subtle.digest('SHA-256', encoder.encode(data));
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

/** Deterministic JSON serialization for fingerprinting */
function stableStringify(obj: any): string {
  if (obj === null || obj === undefined) return '';
  if (typeof obj !== 'object') return String(obj);
  if (Array.isArray(obj)) return `[${obj.map(stableStringify).join(',')}]`;
  return `{${Object.keys(obj).sort().map(k => `${k}:${stableStringify(obj[k])}`).join(',')}}`;
}

// Domain detection from source + data shape
const DOMAIN_MAP: Record<string, string> = {
  hubspot: 'crm', salesforce: 'crm', pipedrive: 'crm',
  slack: 'communication', discord: 'communication', teams: 'communication',
  github: 'engineering', gitlab: 'engineering', linear: 'engineering', jira: 'engineering', asana: 'engineering',
  stripe: 'billing', chargebee: 'billing', paddle: 'billing',
  zendesk: 'support', intercom: 'support', freshdesk: 'support',
  notion: 'productivity', google: 'productivity', confluence: 'productivity',
  mixpanel: 'analytics', amplitude: 'analytics', segment: 'analytics',
  mailchimp: 'marketing', sendgrid: 'marketing',
};

// Entity type keywords for data_kind detection
const ENTITY_KEYWORDS = ['contact', 'company', 'account', 'deal', 'opportunity', 'user', 'organization', 'lead'];
const ACTIVITY_KEYWORDS = ['message', 'comment', 'note', 'call', 'email', 'meeting', 'event'];
const EVENT_KEYWORDS = ['webhook', 'notification', 'alert', 'trigger', 'action'];

// PII regex patterns
const PII_PATTERNS: [string, RegExp][] = [
  ['email', /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/],
  ['phone', /\b(\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/],
  ['ssn', /\b\d{3}-\d{2}-\d{4}\b/],
  ['credit_card', /\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b/],
];

// Canonical field mapping per domain
const CANONICAL_FIELDS: Record<string, Record<string, string>> = {
  crm: {
    firstname: 'first_name', first_name: 'first_name', firstName: 'first_name',
    lastname: 'last_name', last_name: 'last_name', lastName: 'last_name',
    email: 'email', emailaddress: 'email', email_address: 'email',
    company: 'company_name', companyname: 'company_name', company_name: 'company_name',
    phone: 'phone', phonenumber: 'phone', phone_number: 'phone',
    title: 'title', jobtitle: 'title', job_title: 'title',
    website: 'website', url: 'website',
    dealname: 'deal_name', deal_name: 'deal_name', name: 'name',
    amount: 'amount', value: 'amount', dealvalue: 'amount',
    stage: 'stage', dealstage: 'stage', pipeline_stage: 'stage',
    closedate: 'close_date', close_date: 'close_date',
    owner: 'owner_id', ownerid: 'owner_id', owner_id: 'owner_id',
  },
  engineering: {
    title: 'title', summary: 'title',
    description: 'description', body: 'description',
    state: 'status', status: 'status',
    assignee: 'assignee', assigned_to: 'assignee',
    priority: 'priority',
    labels: 'labels', tags: 'labels',
    repository: 'repository', repo: 'repository',
    number: 'number', key: 'number',
  },
  support: {
    subject: 'title', title: 'title',
    description: 'description', body: 'description',
    status: 'status', state: 'status',
    priority: 'priority', urgency: 'priority',
    assignee: 'assignee', assigned_to: 'assignee',
    requester: 'requester', customer: 'requester',
    tags: 'labels',
  },
};

// Required fields per entity type
const REQUIRED_FIELDS: Record<string, string[]> = {
  contact: ['email'],
  deal: ['deal_name'],
  account: ['company_name'],
  ticket: ['title'],
  issue: ['title'],
  message: ['text'],
};

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s-]+/g, '_')
    .toLowerCase();
}

// ─── Stage Implementations ───────────────────────────────────────────────

/**
 * S1: Analyzer — Fingerprint the payload, create envelope
 */
async function stage1_Analyzer(data: any, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const serialized = stableStringify(data);
  const fingerprint = await sha256(`${ctx.tenant_id}:${ctx.source}:${serialized}`);

  const envelope: PipelineEnvelope = {
    raw: data,
    fingerprint,
    meta: {
      source: ctx.source,
      tenant_id: ctx.tenant_id,
      request_id: ctx.requestId,
      received_at: new Date().toISOString(),
      data_kind: 'unknown',
      domain: DOMAIN_MAP[ctx.source] || 'general',
      sensitivity: 'internal',
      pii_fields: [],
      entity_type: '',
      is_duplicate: false,
      validation_errors: [],
      validation_warnings: [],
    },
    canonical: {},
    write_plan: { spine: false, context_store: false, audit: true, targets: ['audit'] },
    children: [],
  };

  console.log(`[S1:Analyzer] fingerprint=${fingerprint.slice(0, 12)}… source=${ctx.source} tenant=${ctx.tenant_id}`);
  return envelope;
}

/**
 * S2: Classifier — Detect data_kind, domain, PII sensitivity
 */
async function stage2_Classifier(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const raw = envelope.raw;
  const jsonStr = JSON.stringify(raw).toLowerCase();

  // Detect data_kind from content shape
  const entityScore = ENTITY_KEYWORDS.filter(k => jsonStr.includes(k)).length;
  const activityScore = ACTIVITY_KEYWORDS.filter(k => jsonStr.includes(k)).length;
  const eventScore = EVENT_KEYWORDS.filter(k => jsonStr.includes(k)).length;

  if (entityScore > activityScore && entityScore > eventScore) {
    envelope.meta.data_kind = 'entity';
  } else if (activityScore > eventScore) {
    envelope.meta.data_kind = 'activity';
  } else if (eventScore > 0) {
    envelope.meta.data_kind = 'event';
  }

  // Derive entity_type from __meta or field inspection
  if (raw?.__meta?.event_type) {
    envelope.meta.entity_type = raw.__meta.event_type.split('.').pop() || 'generic';
  } else if (raw?.type) {
    envelope.meta.entity_type = String(raw.type);
  } else if (raw?.object) {
    envelope.meta.entity_type = String(raw.object);
  } else {
    // Guess from presence of key fields
    if (raw?.email || raw?.first_name || raw?.firstname) envelope.meta.entity_type = 'contact';
    else if (raw?.deal_name || raw?.dealname || raw?.amount) envelope.meta.entity_type = 'deal';
    else if (raw?.company_name || raw?.companyname) envelope.meta.entity_type = 'account';
    else envelope.meta.entity_type = 'generic';
  }

  // Override domain if category is provided
  if (ctx.category) {
    envelope.meta.domain = ctx.category;
  }

  // PII scan
  const rawStr = JSON.stringify(raw);
  const piiFound: string[] = [];
  for (const [label, pattern] of PII_PATTERNS) {
    if (pattern.test(rawStr)) {
      piiFound.push(label);
    }
  }
  envelope.meta.pii_fields = piiFound;

  if (piiFound.includes('ssn') || piiFound.includes('credit_card')) {
    envelope.meta.sensitivity = 'restricted';
  } else if (piiFound.length > 0) {
    envelope.meta.sensitivity = 'confidential';
  }

  console.log(`[S2:Classifier] kind=${envelope.meta.data_kind} entity=${envelope.meta.entity_type} domain=${envelope.meta.domain} sensitivity=${envelope.meta.sensitivity} pii=[${piiFound}]`);
  return envelope;
}

/**
 * S3: Filter — Idempotency (D1 fingerprint check), tenant validation
 */
async function stage3_Filter(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  // Tenant validation
  if (!ctx.tenant_id || ctx.tenant_id === 'default') {
    envelope.meta.validation_warnings.push('Tenant ID is missing or default');
  }

  // Idempotency check via D1 (if available)
  if (ctx.db) {
    try {
      const existing = await ctx.db
        .prepare('SELECT fingerprint FROM processed_fingerprints WHERE fingerprint = ?')
        .bind(envelope.fingerprint)
        .first();

      if (existing) {
        envelope.meta.is_duplicate = true;
        console.log(`[S3:Filter] DUPLICATE detected — fingerprint=${envelope.fingerprint.slice(0, 12)}…`);
        return envelope;
      }

      // Insert fingerprint for future dedup
      await ctx.db
        .prepare('INSERT INTO processed_fingerprints (fingerprint, tenant_id, source, entity_type) VALUES (?, ?, ?, ?)')
        .bind(envelope.fingerprint, ctx.tenant_id, ctx.source, envelope.meta.entity_type)
        .run();
    } catch (err) {
      // D1 errors shouldn't block pipeline — log and continue
      console.warn(`[S3:Filter] D1 dedup check failed:`, err);
    }
  }

  console.log(`[S3:Filter] duplicate=${envelope.meta.is_duplicate} tenant=${ctx.tenant_id}`);
  return envelope;
}

/**
 * S4: Refiner — Split composites, extract cross-ref IDs, normalize field names
 */
async function stage4_Refiner(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const raw = envelope.raw;

  // Detect and split composite payloads (arrays or nested collections)
  if (Array.isArray(raw)) {
    envelope.children = raw;
    console.log(`[S4:Refiner] Split array payload into ${raw.length} children`);
  } else if (raw?.results && Array.isArray(raw.results)) {
    envelope.children = raw.results;
    console.log(`[S4:Refiner] Split .results into ${raw.results.length} children`);
  } else if (raw?.data && Array.isArray(raw.data)) {
    envelope.children = raw.data;
    console.log(`[S4:Refiner] Split .data into ${raw.data.length} children`);
  } else if (raw?.records && Array.isArray(raw.records)) {
    envelope.children = raw.records;
    console.log(`[S4:Refiner] Split .records into ${raw.records.length} children`);
  }

  // Normalize field names to snake_case on the primary object
  const target = envelope.children.length > 0 ? envelope.children[0] : raw;
  if (target && typeof target === 'object' && !Array.isArray(target)) {
    const normalized: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(target)) {
      if (key.startsWith('__')) {
        normalized[key] = value; // Preserve meta keys
      } else {
        normalized[toSnakeCase(key)] = value;
      }
    }
    // Store normalized back (for single entity)
    if (envelope.children.length === 0) {
      envelope.raw = normalized;
    }
  }

  // Extract cross-reference IDs from the raw data
  const crossRefKeys = ['id', 'external_id', 'hubspot_id', 'salesforce_id', 'stripe_id', 'github_id'];
  for (const key of crossRefKeys) {
    const val = raw?.[key] || raw?.[toSnakeCase(key)];
    if (val) {
      (envelope.canonical as any)[`xref_${key}`] = String(val);
    }
  }

  console.log(`[S4:Refiner] children=${envelope.children.length} crossRefs=${Object.keys(envelope.canonical).filter(k => k.startsWith('xref_')).length}`);
  return envelope;
}

/**
 * S5: Extractor — Map fields to canonical schema
 */
async function stage5_Extractor(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const domain = envelope.meta.domain;
  const fieldMap = CANONICAL_FIELDS[domain] || {};
  const source = envelope.children.length > 0 ? envelope.children[0] : envelope.raw;

  if (source && typeof source === 'object') {
    for (const [rawKey, value] of Object.entries(source)) {
      if (rawKey.startsWith('__')) continue;
      const snakeKey = toSnakeCase(rawKey);
      const canonicalKey = fieldMap[snakeKey] || fieldMap[rawKey];
      if (canonicalKey) {
        envelope.canonical[canonicalKey] = value;
      } else {
        // Keep unmapped fields under their snake_case name
        envelope.canonical[snakeKey] = value;
      }
    }
  }

  // Extract text content for context store
  const textFields = ['description', 'body', 'text', 'content', 'notes', 'summary'];
  const texts: string[] = [];
  for (const field of textFields) {
    const val = (source as any)?.[field];
    if (val && typeof val === 'string' && val.length > 50) {
      texts.push(val);
    }
  }
  if (texts.length > 0) {
    (envelope.canonical as any).__text_content = texts.join('\n\n');
  }

  console.log(`[S5:Extractor] mapped ${Object.keys(envelope.canonical).length} canonical fields, ${texts.length} text blocks`);
  return envelope;
}

/**
 * S6: Validator — Required fields, type checks, warning/error flagging
 */
async function stage6_Validator(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const entityType = envelope.meta.entity_type;
  const required = REQUIRED_FIELDS[entityType] || [];

  // Check required fields
  for (const field of required) {
    if (!envelope.canonical[field]) {
      envelope.meta.validation_errors.push(`Missing required field: ${field}`);
    }
  }

  // Type validations
  const emailVal = envelope.canonical['email'];
  if (emailVal && typeof emailVal === 'string') {
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailVal)) {
      envelope.meta.validation_warnings.push(`Invalid email format: ${emailVal}`);
    }
  }

  // Date field parsing
  const dateFields = ['close_date', 'created_at', 'updated_at', 'due_date'];
  for (const df of dateFields) {
    const val = envelope.canonical[df];
    if (val && typeof val === 'string') {
      const parsed = new Date(val);
      if (isNaN(parsed.getTime())) {
        envelope.meta.validation_warnings.push(`Unparseable date in ${df}: ${val}`);
      } else {
        envelope.canonical[df] = parsed.toISOString();
      }
    }
  }

  // Numeric fields
  if (envelope.canonical['amount'] !== undefined) {
    const num = Number(envelope.canonical['amount']);
    if (isNaN(num)) {
      envelope.meta.validation_warnings.push(`Non-numeric amount: ${envelope.canonical['amount']}`);
    } else {
      envelope.canonical['amount'] = num;
    }
  }

  const errCount = envelope.meta.validation_errors.length;
  const warnCount = envelope.meta.validation_warnings.length;
  console.log(`[S6:Validator] errors=${errCount} warnings=${warnCount}`);
  return envelope;
}

/**
 * S7: Split Router — Generate write plan
 */
async function stage7_SplitRouter(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  const targets: string[] = ['audit']; // Always write audit trace

  // Skip Spine write if duplicate or too many validation errors
  if (envelope.meta.is_duplicate) {
    console.log(`[S7:SplitRouter] Skipping writes — duplicate`);
    envelope.write_plan = { spine: false, context_store: false, audit: true, targets: ['audit'] };
    return envelope;
  }

  if (envelope.meta.validation_errors.length > 3) {
    console.log(`[S7:SplitRouter] Routing to DLQ — ${envelope.meta.validation_errors.length} errors`);
    targets.push('dlq');
    envelope.write_plan = { spine: false, context_store: false, audit: true, targets };
    return envelope;
  }

  // Route to Spine if it's a valid entity or activity
  if (envelope.meta.data_kind === 'entity' || envelope.meta.data_kind === 'activity') {
    targets.push('spine');
    envelope.write_plan.spine = true;
  }

  // Route to Context Store if we extracted text content
  if ((envelope.canonical as any).__text_content) {
    targets.push('context_store');
    envelope.write_plan.context_store = true;
  }

  envelope.write_plan.targets = targets;

  console.log(`[S7:SplitRouter] targets=[${targets}]`);
  return envelope;
}

/**
 * S8: Writers — Execute the write plan (Spine v2, audit, async queue)
 *
 * NOTE: The actual HTTP calls to Spine/Normalizer happen in pipeline.ts processIncoming().
 * This stage prepares the final payload shape and logs the audit trace.
 * Heavy writes are deferred to the existing pipeline.ts flow.
 */
async function stage8_Writers(envelope: PipelineEnvelope, ctx: IngestionContext): Promise<PipelineEnvelope> {
  // Audit trace (always)
  console.log(`[S8:Writers] audit trace: request=${ctx.requestId} fp=${envelope.fingerprint.slice(0, 12)}… targets=[${envelope.write_plan.targets}]`);

  // Enqueue for async AI analysis
  if (ctx.thinkQueue && envelope.write_plan.spine) {
    try {
      await ctx.thinkQueue.send({
        tenant_id: ctx.tenant_id,
        entity_type: envelope.meta.entity_type,
        fingerprint: envelope.fingerprint,
        canonical: envelope.canonical,
        source: ctx.source,
        request_id: ctx.requestId,
      });
      console.log(`[S8:Writers] Enqueued to THINK_QUEUE`);
    } catch (err) {
      console.warn(`[S8:Writers] THINK_QUEUE send failed:`, err);
    }
  }

  return envelope;
}

// ─── Pipeline Orchestrator ────────────────────────────────────────────────

/**
 * Run all 8 stages sequentially.
 * Returns the enriched envelope (or the original data wrapped in an envelope).
 *
 * Callers (pipeline.ts processIncoming) use the returned envelope to decide
 * whether to proceed with normalization + Spine storage.
 */
export async function run8StagePipeline(data: any, ctx: IngestionContext): Promise<any> {
  let envelope: PipelineEnvelope;

  // S1: Analyzer
  envelope = await stage1_Analyzer(data, ctx);

  // S2: Classifier
  envelope = await stage2_Classifier(envelope, ctx);

  // S3: Filter (dedup)
  envelope = await stage3_Filter(envelope, ctx);

  // Short-circuit on duplicate
  if (envelope.meta.is_duplicate) {
    console.log(`[Pipeline] Duplicate detected — returning early`);
    return {
      ...envelope.canonical,
      __pipeline: {
        fingerprint: envelope.fingerprint,
        is_duplicate: true,
        skipped: true,
      },
    };
  }

  // S4: Refiner
  envelope = await stage4_Refiner(envelope, ctx);

  // S5: Extractor
  envelope = await stage5_Extractor(envelope, ctx);

  // S6: Validator
  envelope = await stage6_Validator(envelope, ctx);

  // S7: Split Router
  envelope = await stage7_SplitRouter(envelope, ctx);

  // S8: Writers
  envelope = await stage8_Writers(envelope, ctx);

  // Return enriched data for downstream (Normalizer + Spine in pipeline.ts)
  return {
    ...envelope.canonical,
    __pipeline: {
      fingerprint: envelope.fingerprint,
      data_kind: envelope.meta.data_kind,
      domain: envelope.meta.domain,
      entity_type: envelope.meta.entity_type,
      sensitivity: envelope.meta.sensitivity,
      pii_fields: envelope.meta.pii_fields,
      is_duplicate: false,
      validation_errors: envelope.meta.validation_errors,
      validation_warnings: envelope.meta.validation_warnings,
      write_plan: envelope.write_plan,
      children_count: envelope.children.length,
    },
    __meta: data?.__meta, // Preserve upstream meta
  };
}
